name: UI Tests

on:
  workflow_call:
    inputs:
      branch:
        description: 'The branch to use'
        default: 'main'
        required: false
        type: string
      wallet-url:
        description: 'The wallet url'
        default: 'https://react-wallet.walletconnect.com/'
        required: false
        type: string
      command:
        description: 'The test command to run'
        default: 'playwright:test'
        required: false
        type: string
      skip-playwright-webserver:
        description: 'Skip setting up a local test server'
        default: false
        required: false
        type: boolean
      secure-site-url:
        description: 'Secure site SDK url'
        default: 'https://secure.walletconnect.org/sdk'
        required: false
        type: string
    secrets:
      NEXT_PUBLIC_PROJECT_ID:
        required: true
      TESTS_NEXTAUTH_SECRET:
        required: false
      TESTS_MAILSAC_API_KEY:
        required: false
      TESTS_SOCIAL_EMAIL:
        required: false
      TESTS_SOCIAL_PASSWORD:
        required: false
      EIP155_PRIVATE_KEY:
        required: false
      SOLANA_PRIVATE_KEY:
        required: false

jobs:
  ui_tests:
    name: 'Playwright Tests'
    runs-on: [self-hosted, aws-ecs-16cpu-64mem-30m]
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]
        shardTotal: [5]
    timeout-minutes: 20
    steps:
      # Possibly this helps with GitHub-hosted runner network issues, but it's not confirmed
      # It's not supported in self-hosted runners, however, so commenting it out for now
      # - name: Tune GitHub-hosted runner network
      #   uses: smorimoto/tune-github-hosted-runner-network@v1

      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: reown-com/appkit
          ref: ${{ inputs.branch }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Waiting for Vercel deployment
        uses: mskelton/wait-for-vercel-action@v1
        id: wait-for-vercel
        with:
          prod-url: appkit-lab.reown.com
          token: ${{ secrets.VERCEL_TOKEN }}
          await-build: true

      - name: Build extension
        env:
          EIP155_PRIVATE_KEY: ${{ secrets.EIP155_PRIVATE_KEY }}
          SOLANA_PRIVATE_KEY: ${{ secrets.SOLANA_PRIVATE_KEY }}
        working-directory: ./apps/browser-extension/
        run: pnpm build

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        working-directory: ./apps/laboratory/
        run: pnpm playwright:install

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ steps.wait-for-vercel.outputs.url }}
          WALLET_URL: ${{ inputs.wallet-url }}
          NEXT_PUBLIC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
          SKIP_PLAYWRIGHT_WEBSERVER: ${{ inputs.skip-playwright-webserver }}
          NEXTAUTH_SECRET: ${{ secrets.TESTS_NEXTAUTH_SECRET }}
          MAILSAC_API_KEY: ${{ secrets.TESTS_MAILSAC_API_KEY }}
          NEXT_PUBLIC_SECURE_SITE_SDK_URL: ${{ inputs.secure-site-url }}
          SOCIAL_TEST_EMAIL: ${{ secrets.TESTS_SOCIAL_EMAIL }}
          SOCIAL_TEST_PASSWORD: ${{ secrets.TESTS_SOCIAL_PASSWORD }}
          CI: true
        working-directory: ./apps/laboratory/
        run: pnpm ${{ inputs.command }} --shard=${{ matrix.shard }}/${{ matrix.shardTotal }}

      # Disable temporarily
      # - name: Run canary with minimal environment config
      #   env:
      #     # DO NOT MODIFY THIS. If you are required to add variables here without adding
      #     # them to the rs-relay repo it will cause alarms.
      #     NEXT_PUBLIC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
      #     NEXTAUTH_SECRET: ${{ secrets.TESTS_NEXTAUTH_SECRET }}
      #     CI: true
      #   working-directory: ./apps/laboratory/
      #   run: pnpm playwright:test:canary

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report-${{ matrix.shard }}
          path: ./apps/laboratory/playwright-report/
          retention-days: 7
